name: CI - .NET Clean Architecture
on:
  push:
    branches: [ main, master, develop, "feature/**", "fix/**", "refactor/**", "docs/**", "test/**", "chore/**" ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - shell: pwsh
        run: dotnet restore .\Crud_Clientes.sln
      - shell: pwsh
        run: dotnet build .\Crud_Clientes.sln --configuration Release --no-restore
      - shell: pwsh
        run: dotnet test .\Crud_Clientes.sln --configuration Release --no-build --collect:"XPlat Code Coverage"
